spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3039"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

security:
  jwt:
    secret-key: 3c796d818fa4dd544f4a0d2d3781e43d0c1cdf464a722f5a604ac6c0ee957279

#  cloud:
#    gateway:
#      - discovery:
#        locator:
#          enabled=true:
#      - routes:
#        - id: user-service
#        - uri: lb://user-service
#        - predicates:
#            - Path=/api/users/**
#
#        - id: workspace-service
#        - uri: lb://workspace-service
#        - predicates:
#            - Path=/api/workspaces/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
#    org.springframework.cloud.loadbalancer: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG




