spring:
  application:
    name: storage-service

  cloud:
    aws:
      credentials:
        access-key: AKIAZI2LFJRYYN36F2M7
        secret-key: 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
      s3:
        region: me-central-1
        bucket: atosinternship

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#    codec:
#      max-in-memory-size: 10MB

server:
    port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
#    root: DEBUG
#    org.springframework: DEBUG
    org.springframework.web: TRACE
    org.springframework.data: TRACE
    org.springframework.security: TRACE
